package trex.analysis;

import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintStream;

import msutil.Composition;
import msutil.Peak;
import msutil.SpectraIterator;
import msutil.Spectrum;

import parser.BufferedLineReader;
import parser.MgfSpectrumParser;

public class tmp {
	
	public static void main(String[] argv) throws IOException{
		
		String a1 = "MFSFVDLRLLLLLAATALLTHGQEEGQEEDIPPVTCVQNGLRYYDRDVWKPEACRICVCDNGNVLCDDVICDETKNCPGAQVPPGECCPVCPDGEASPTDQETTGVEGPKGDTGPRGPRGPAGPPGRDGIPGQPGLPGPPGPPGPPGPPGLGGNFAPQMSYGYDEKSTGGISVPGPMGPSGPRGLPGPPGAPGPQGFQGPPGEPGEPGASGPMGPRGPPGPPGKNGDDGEAGKPGRPGERGPPGPQGARGLPGTAGLPGMKGHRGFSGLDGAKGDAGPAGPKGEPGSPGENGAPGQMGPRGLPGERGRPGAPGPAGARGNDGATGAAGPPGPTGPAGPPGFPGAVGAKGEAGPQGARGSEGPQGVRGEPGPPGPAGAAGPAGNPGADGQPGAKGANGAPGIAGAPGFPGARGPSGPQGPSGPPGPKGNSGEPGAPGNKGDTGAKGEPGPTGIQGPPGPAGEEGKRGARGEPGPTGLPGPPGERGGPGSRGFPGADGVAGPKGPAGERGSPGPAGPKGSPGEAGRPGEAGLPGAKGLTGSPGSPGPDGKTGPPGPAGQDGRPGPPGPPGARGQAGVMGFPGPKGAAGEPGKAGERGVPGPPGAVGPAGKDGEAGAQGPPGPAGPAGERGEQGPAGSPGFQGLPGPAGPPGEAGKPGEQGVPGDLGAPGPSGARGERGFPGERGVQGPPGPAGPRGANGAPGNDGAKGDAGAPGAPGSQGAPGLQGMPGERGAAGLPGPKGDRGDAGPKGADGSPGKDGVRGLTGPIGPPGPAGAPGDKGEAGPSGPAGPTGARGAPGDRGEPGPPGPAGFAGPPGADGQPGAKGEPGDAGAKGDAGPPGPAGPTGPPGPIGNVGAPGPKGARGSAGPPGATGFPGAAGRVGPPGPSGNAGPPGPPGPAGKEGGKGARGETGPAGRPGEVGPPGPPGPAGEKGSPGADGPAGAPGTPGPQGIAGQRGVVGLPGQRGERGFPGLPGPSGEPGKQGPSGTSGERGPPGPMGPPGLAGPPGESGREGSPGAEGSPGRDGSPGPKGDRGETGPAGPPGAPGAPGAPGPVGPAGKNGDRGETGPAGPAGPIGPVGARGPAGPQGPRGDKGETGEQGDRGIKGHRGFSGLQGPPGPPGSPGEQGPSGASGPAGPRGPPGSAGSPGKDGLNGLPGPIGPPGPRGRTGDAGPVGPPGPPGPPGPPGPPSGGFDFSFLPQPPQEKAHDGGRYYRADDANVVRDRDLEVDTTLKSLSQQIENIRSPEGSRKNPARTCRDLKMCHSDWKSGEYWIDPNQGCNLDAIKVFCNMETGETCVYPTQPQVAQKNWYISKNPKEKRHVWYGESMTDGFQFEYGGQGSDPADVAIQLTFLRLMSTEASQNITYHCKNSVAYMDQQTGNLKKALLLQGSNEIEIRAEGNSRFTYSVTYDGCTSHTGAWGKTVIEYKTTKTSRLPIIDVAPLDVGAPDQEFGMDIGPVCFL";
		String a2 = "MFSFVDLRLLLLVAATALLTHGQEEGQEEDIPPVTCVQNGLRYYDRDVWKPEACRICVCDNGNVLCDDVICDETKNCPGAQVPPGECCPVCPDGEASPTDQETTGVEGPKGDTGPRGPRGPAGPPGRDGIPGQPGLPGPPGPPGPPGPPGLGGNFAPQMSYGYDEKSTGGISVPGPMGPSGPRGLPGPPGAPGPQGFQGPPGEPGEPGASGPMGPRGPPGPPGKNGDDGEAGKPGRPGERGPPGPQGARGLPGTAGLPGMKGHRGFSGLDGAKGDAGPAGPKGEPGSPGENGAPGQMGPRGLPGERGRPGAPGPAGARGNDGATGAAGPPGPTGPAGPPGFPGAVGAKGEAGPQGARGSEGPQGVRGEPGPPGPAGAAGPAGNPGADGQPGAKGANGAPGIAGAPGFPGARGPSGPQGPSGPPGPKGNSGEPGAPGNKGDTGAKGEPGPTGIQGPPGPAGEEGKRGARGEPGPTGLPGPPGERGGPGSRGFPGADGVAGPKGPAGERGSPGPAGPKGSPGEAGRPGEAGLPGAKGLTGSPGSPGPDGKTGPPGPAGQDGRPGPPGPPGARGQAGVMGFPGPKGAAGEPGKAGERGVPGPPGAVGPAGKDGEAGAQGPPGPAGPAGERGEQGPAGSPGFQGLPGPAGPPGEAGKPGEQGVPGDLGAPGPSGARGERGFPGERGVQGPPGPAGPRGANGAPGNDGAKGDAGAPGAPGSQGAPGLQGMPGERGAAGLPGPKGDRGDAGPKGADGSPGKDGVRGLTGPIGPPGPAGAPGDKGEAGPSGPAGPTGARGAPGDRGEPGPPGPAGFAGPPGADGQPGAKGEPGDAGAKGDAGPPGPAGPTGPPGPIGNVGAPGPKGARGSAGPPGATGFPGAAGRVGPPGPSGNAGPPGPPGPAGKEGGKGPRGETGPAGRPGEVGPPGPPGPAGEKGSPGADGPAGAPGTPGPQGIAGQRGVVGLPGQRGERGFPGLPGPSGEPGKQGPSGASGERGPPGPMGPPGLAGPPGESGREGSPGAEGSPGRDGSPGPKGDRGETGPAGPPGAPGAPGAPGPVGPAGKSGDRGETGPAGPAGPIGPVGARGPAGPQGPRGDKGETGEQGDRGIKGHRGFSGLQGPPGPPGSPGEQGPSGASGPAGPRGPPGSAGSPGKDGLNGLPGPIGPPGPRGRTGDAGPVGPPGPPGPPGPPGPPSGGFDFSFLPQPPQEKAHDGGRYYRADDANVVRDRDLEVDTTLKSLSQQIENIRSPEGSRKNPARTCRDLKMCHSDWKSGEYWIDPNQGCNLDAIKVFCNMETGETCVYPTQPHVAQKNWYISKNPKEKRHVWYGESMTDGFQFEYGGQGSDPADVAIQLTFLRLMSTEASQNITYHCKNSVAYMDQQTGNLKKALLLQGSNEIEIRAEGNSRFTYSVTYDGCTSHTGAWGKTVIEYKTTKTSRLPIIDVAPLDVGAPDQEFGMDVGPVCFL";
		int j=0;
		for(int i=0; i<a1.length(); i++){
			if(a1.charAt(i) != a2.charAt(i)) {
				System.out.print("*" + i); j++;
			}
			//else System.out.print(a1.charAt(i));
		}
		System.out.println("\n" + j);
		/*
		FileOutputStream mgfout= null;
		PrintStream ps = null;
		
		mgfout = new FileOutputStream("/home/kwj/workspace/inputs/Had/Hadrosaur_14217_Orbitrap.mgf2");
		ps = new PrintStream(mgfout);
			
		SpectraIterator iterator = new SpectraIterator("/home/kwj/workspace/inputs/Had/Hadrosaur_14217_Orbitrap.mgf", new MgfSpectrumParser());
		
		while(iterator.hasNext())
		{
			Spectrum origSpec = null;
			if(iterator!=null )
				origSpec = iterator.next();
			//System.out.println(origSpec.getParentMass() + "b");
			Peak precursor = origSpec.getPrecursorPeak();
			float mz = (precursor.getMz()+(precursor.getCharge()-1)*Composition.H)/precursor.getCharge();
			
			precursor.setMz(mz);
			origSpec.outputMgf(ps);
			//System.out.println(origSpec.getParentMass() + "a");

		}
		
		ps.close();
		mgfout.close();
		
		*/
		/*
		for(int i=1;i<40;i++){
			out = 
				new BufferedWriter(new FileWriter("/home/kwj/cave_panda"+i+".txt"));
			
			out.write("OutputFile /data/kyjeong/inputs/cavebear/panda"+i+".out\n");
			out.write("InputFile /data/kyjeong/inputs/cavebear/\n");
			out.write("DBFile /data/kyjeong/inputs/DataBases/Panda6Frame/panda_pro"+i+".fasta\n");
			out.write("SpecProb 1e-10\n");
			out.write("isSpecProbExclusive true\n");
			out.write("RankScorerFile /data/kyjeong/inputs/ionstat_iontrap.txt\n");
			out.write("AminoAcidFile /data/kyjeong/inputs/cavebear/AASetWithHydroProline.txt\n");
			out.write("MSGFScore 50\n");
			out.close();
		}
		*/
		
		/*
		for(int i=1;i<40;i++){
			out = 
				new BufferedWriter(new FileWriter("/home/kwj/cave_panda"+i+".sh"));
			
			out.write("#!/bin/bash\n");
			out.write("#\n");
			out.write("#$ -cwd\n");
			out.write("#$ -j y\n");
			out.write("#$ -S /bin/bash\n");
			out.write("#\n");
			out.write("java -jar -Xmx8000m -ea /data/kyjeong/MSgap.jar /data/kyjeong/cave_panda"+i+".txt");
			out.close();
		}
		*/
		/*
		String s;
		//126272267
		long num = 0;
		int fileIndex = 1;
		int numTh = (130302600)/2;
		
		while((s=in.readLine()) != null){
			if(s.startsWith(">")){
				if(num > numTh){
					out.close();
					num = 0;
					fileIndex++;
				//	if(fileIndex>21) break;
				}
				if(num == 0)
					out =  new BufferedWriter(new FileWriter("/home/kwj/workspace/inputs/DataBases/Panda6Frame/panda"+fileIndex+".fasta"));
				
				//System.out.println(num);	
			}
			out.write(s+"\n");
			num+=s.length()+1;
		}
		in.close();
		out.close();
		*/
	}
}
